"""Part 0 (project map) and Part A (primer from zero) of the working notebook."""


def part0(nb):
    nb.title("CENIC on the GPU — working notebook (comprehensive edition)")
    nb.p("For: Marco. Purpose: everything about this project in one place, from zero background, so every gap the agents left can be seen and filled. Deadline 2026-09-01. Paper structure per ~/Documents/code/CLAUDE.md. Generated 2026-08-29; Part 0, D1 and the audit entry B29 refreshed 2026-08-30 against the consolidated tree. Built from the repositories, the results write-ups, the optimization ledger, the provenance audit, the literature review, the hardware brief and the memory files; every source is named where it is used.", italic=True)
    nb.p("How this notebook is organized", bold=True)
    nb.bl(["Part 0 — Project map: the goal, the hypothesis, the three repositories, the dated timeline of the whole effort, the deliverables that exist.",
           "Part A — Primer from zero: physics of contact → numerics → MuJoCo vs convex solvers → error control and CENIC → GPU realities → what we built (both adaptive solvers, in detail) → the RL platform and the arm.",
           "Part B — Every experiment, one fixed template each: background and motivation, the question, the design, what the figure/table says number by number, what it does NOT show, where it lives, status, gaps for you to fill. B1 the killer-experiment logic; B2–B16 Part 1 (pure solver); B17–B25 Part 2 (the training program: platform, tasks, ladders, smokes, rulings); B28 the hardware/deployment brief.",
           "Part C — The paper, section by section: purpose line, questions, evidence pointers, blank lines, status boxes. No text written for you.",
           "Part D — Fact bank (every measured number with its source), open decisions, repo map and re-run commands, deadline plan.",
           "Part E — Glossary. Appendix F — MuJoCo solref/solimp in full. Appendix G — the speed contributions inventory. Appendix H — the literature review, theme by theme."])
    nb.h("0.1 The goal and the hypothesis (CLAUDE.md, verbatim in substance)", 1)
    nb.p("Goal: show that per-world adaptive time-stepping enables robot learning that fixed-step simulation cannot. Two solver variants: SolverMuJoCoAdaptive and SolverICFAdaptive (the ICF convex contact model). Both are convex solvers inside NVIDIA Newton where each parallel world advances its own inner time step between fixed outer control boundaries, driven by an on-GPU step-doubling error controller (no PCIe transfers in the physics loop).")
    nb.p("Success = the killer experiment: a physically achievable task where a policy trained under fixed step fails or learns an artifact exploit, and the same task — same scene, same reward, same seeds, solver type the only variable — trains to a working policy under adaptive stepping. Wall-time claims are made at matched accuracy, never against a fixed step large enough to produce the artifacts. The regime that matters is STIFF CONTACT: that is where fixed-step MuJoCo is expected to fail and where adaptive ICF has to train the policy.")
    nb.p("Paper (PI meeting 2026-08-25): contributions = CENIC running on GPU; adaptive Warp implementation; speed optimizations. Structure = Intro/Motivations/Background → CENIC implementation + speed optimizations → Results part 1 (pure solver: fixed-mujoco, adaptive-mujoco, fixed-icf, adaptive-icf) → Results part 2 (application: slide mug, pick up mug, plate from dish rack, mug on tree, flip mug) → IRL (flip, slide on the Trossen arm).")
    nb.p("Epistemics rule that governs every number in this notebook: 'validated' means shipped by the upstream team; anything authored in our forks is unvalidated until measured in the current session; prose in comments/commits/ledgers is folklore until the cited probe is re-run. Where I quote a ledger or a commit message below I say so.", italic=True)
    nb.h("0.2 The three repositories and the sibling solver repos", 1)
    nb.tbl([["Repo", "What it is", "Branch / state", "What lives there for the paper"],
            ["newton-adaptive", "fork of newton-physics/newton", "parity/icf-march (HEAD 25cba204 2026-08-30)", "SolverMuJoCoAdaptive, adaptive_boundary.py (the Part-1 bench suite moved to icra2027/part1 on 08-30)"],
            ["icf_warp_adaptive", "sibling repo (joined by ICF_WARP_PATH)", "perf/contact-solve @ 04eabc9 (2026-08-24)", "SolverICF and SolverICFAdaptive — the ICF arms; DEVIATIONS.md (six live deviations from CENIC); contact_law.py, kernels_dof.py (implicit PD)"],
            ["IsaacLab", "fork of isaac-sim/IsaacLab", "develop (synced 2026-08-30)", "the Part-2 tasks (trossen_mug_lift, _slide, _plate_rack, _mug_flip, _mug_tree; _mug_rack out of scope), the Newton manager and solver plumbing, probes, campaign script, logs/rsl_rl runs, wandb/"],
            ["icra2027", "platform layer + the venv both repos run in", "main", "the Python (.venv); part1/ (bench suite, scenes, results); paper/ (this package); part2/ (pointer into IsaacLab); tools/"],
            ["cenic-paper", "symlink to icra2027/paper (inside the icra2027 git repo)", "~/Documents/code/cenic-paper → icra2027/paper", "conference_101719.tex (IEEE template verbatim), main.tex (bare outline), figures/, references.bib, this notebook; the history reports moved to ~/Documents/code/cenic-paper-archive/notebook_sources/"]])
    nb.h("0.3 Where every component stands today (active state only; history is in notebook_sources/)", 1)
    nb.tbl([["Component", "State now", "Used by the paper?"],
            ["SolverMuJoCoAdaptive", "at ICF-march parity since 2026-08-24 (elementary Drake law, exhaustion = divergence, absolute error test, two geometry queries per attempt); benches use march budget 4096 (65536 on work-precision)", "yes — the MuJoCo error-control arm"],
            ["SolverICF / SolverICFAdaptive (icf_warp_adaptive @ 04eabc9)", "the reference arm (the slide pair trained on it); default march only (PI controller reverted 08-24); six documented deviations from CENIC", "yes — both ICF arms, Part 1 and Part 2"],
            ["SolverMuJoCo (fixed)", "explicit calibrated solref per scene in Part 1; MuJoCo default solref (0.02, 1) in the training scenes", "yes — the MuJoCo fixed arm (Part 2 MuJoCo runs still to be made)"],
            ["Part-1 bench suite", "complete: 24 figure PDFs, 8 tables, PART1.md, literature review; all regenerable; lives in icra2027/part1", "yes"],
            ["Part-2 tasks", "slide, lift, plate, flip, tree packages on the develop branch (flip redesigned 08-28/29; rack exists, out of scope)", "yes"],
            ["Campaign protocol", "LAUNCHED 2026-08-30 14:36: 35 runs (K1–K5 + adaptive + K5wall × 5 tasks), W&B project icra2027; MuJoCo arms a separate pass", "yes"],
            ["Hardware", "WXAI brief delivered; no hardware run recorded here", "IRL section"],
            ["Paper package", "IEEE template verbatim + bare outline + figures + refs + this notebook", "yes"]])
    nb.h("0.4 Deliverables that exist today", 1)
    nb.bl(["Part 1: 24 committed figure PDFs + 8 tables + PART1.md (setup, protocol, captions, results) + PART1_LITERATURE.md — all regenerable from committed CSVs and scripts.",
           "Solvers: SolverMuJoCoAdaptive (at parity with the ICF march) and SolverICF/SolverICFAdaptive (the reference arm the slide pair trained on).",
           "Part 2: five task packages in the campaign (lift, slide, plate, flip, tree; rack out of scope), the campaign script, the live campaign on W&B project icra2027 (the smoke* series stays on rubato-trossen), probes.",
           "Paper package: IEEE template verbatim + bare outline + references + figures + this notebook.",
           "Not on disk: any K3wall (wall-matched fixed) run; any MuJoCo-fixed run on a mug task; any mug-on-tree asset; a committed before/after probe for the speed optimizations on a paper scene; hardware results."])


def partA(nb):
    nb.pagebreak()
    nb.title("Part A — Primer from zero")
    nb.h("A1. What a physics simulator does, and where the time step comes in", 1)
    nb.p("A rigid-body simulator holds a state x = (q, v): positions/orientations q of every body and their velocities v. Once per step it (1) finds which bodies touch (collision detection → contact points, each with a signed distance φ: negative means overlap), (2) computes forces — gravity, joint motors, contact — and (3) advances the state by a time step δt. Everything a policy sees comes from repeating this.")
    nb.p("The step δt is a modeling decision, not a detail. Large steps are cheap but the solver only 'looks' at the world every δt: fast events between looks are missed or mangled. Small steps are faithful but cost proportionally more. Contact is the fast event: a 65 g sphere on a 10⁵ N/m spring oscillates at ω = √(k/m) ≈ 1240 rad/s, one cycle every 5 ms — already shorter than a 10 ms control step.")
    nb.box("Why robot learning makes this worse", "RL runs thousands of worlds in parallel on one GPU and the policy acts at a fixed control rate (ours: 30 Hz in training, 10 ms boundaries in the benches). The simulator must deliver a state at every boundary for every world. The cheapest way is one step per boundary — exactly the step at which stiff contact goes wrong — and a policy is an optimizer that will find and exploit whatever goes wrong (B1, B17).")
    nb.p("What 'goes wrong' looks like (all measured in this project):", bold=True)
    nb.bl(["Softening: the solver realizes a much lower stiffness than the model asks for (MuJoCo at 10 ms caps near 10³ N/m when the model says 10⁵; B3).",
           "Penetration: bodies sink far deeper than the model's resting depth (B6).",
           "Passthrough / ejection: a body moving 2.8 cm per step with a 2.5 cm radius sees its first contact past its centre and can be launched — the mechanism behind the retired pre-fix ejections; on the corrected scene no arm ejects at any setting (B6).",
           "Instability: an explicit joint gain diverges when √(K_p/m)·δt ≳ 2 (MuJoCo at K_p = 10⁵ for δt ≥ 5 ms; B12).",
           "Hidden chatter: a stiff PD driven by a held 100 Hz target kicks its fingertip 300 N per step; at 10 ms the step integrates the rattle away and the policy never sees it (B12).",
           "Hopping/rocking: MuJoCo's pushed box lifts 2–58 mm and pitches at 1–3 rad/s where the physics says it slides flat (B12).",
           "In training: 'the policy learns to crush the mug until the solve breaks' (IsaacLab bc8e951e89) — the divergence exit had to be priced at −50; 'flick farming' and 'the in-cup exploit' were reward exploits closed by gating (B25)."])

    nb.h("A2. Compliant contact: the model we simulate", 1)
    nb.p("Rigid contact says 'bodies never overlap' — a constraint (impulses, complementarity). Compliant contact says 'overlap produces a restoring force', a very stiff spring. The point-contact law used by ICF/CENIC (CENIC eq. 5–6):")
    nb.p("    f_e(q) = k · max(0, −φ(q))          normal elastic force; φ < 0 is the penetration depth", italic=True)
    nb.p("    f_n(x) = f_e(q) · max(0, 1 − d·v_n)   Hunt & Crossley dissipation; v_n = normal separation velocity; d [s/m]", italic=True)
    nb.p("Friction is Coulomb with coefficient μ, regularized: the tangential force ramps up linearly over a stiction tolerance velocity v_s and saturates at μ f_n beyond it (CENIC eq. 14: γ_t = −μ · v_t/√(‖v_t‖² + v_s²) · γ_n). Small v_s ≈ rigid Coulomb friction (hard clutter, v_s = 0.1 mm/s); large v_s is creepy friction (soft clutter, 1 cm/s). The ICF paper proves the 'gliding' offset μ(δt + τ_d)‖v_t‖ of MuJoCo-type regularizations does not vanish with the step — one reason the model, not the step, should own friction.")
    nb.p("Three numbers to derive on a napkin (they are the yardsticks of every artifact figure):", bold=True)
    nb.tbl([["Quantity", "Formula", "65 g sphere, k = 10⁵ N/m", "0.1 kg ball, k = 10³", "1 kg box on 4 corners, k = 10⁵"],
            ["Resting depth", "m g / k (per contact; /n for n contacts sharing the load)", "6.4 µm", "0.98 mm", "25 µm"],
            ["Impact depth (drop at speed v)", "v √(m/k)", "2.3 mm at 2.8 m/s", "44 mm at 4.4 m/s (linear-spring estimate)", "—"],
            ["Contact duration", "π √(m/k)", "2.5 ms", "31 ms", "—"]])
    nb.p("Stiffness is a MODEL parameter in ICF: the solver must realize it whatever δt is. In MuJoCo it is not (A3, Appendix F). 'Soft' vs 'hard' in this project means k = 10³ vs 10⁵ N/m (CENIC's two clutter scenes), not soft bodies. In the training scenes the ICF stiffness is a GLOBAL IcfParams value (ICF_CONTACT_STIFFNESS; the authored per-shape ke = 4.6e7 is inert for ICF — ledger pass 38 and IsaacLab manager comment), which is one of the open questions in B21.", italic=True)

    nb.h("A3. How a step is computed: explicit, implicit, and MuJoCo's soft constraints", 1)
    nb.p("Explicit stepping evaluates forces at the start of the step and pushes: v_{n+1} = v_n + δt·f(x_n)/m. For a spring this is unstable unless ω·δt ≲ 2. Implicit stepping solves for the end-of-step velocity with the force at the end: stable for any δt, at the price of first-order accuracy (error ∝ δt) and numerical damping. Both adaptive arms are first-order implicit in this sense; CENIC's step-doubling gives them a second-order error ESTIMATE, not second-order accuracy.")
    nb.p("MuJoCo's contact is a soft constraint, not a spring on the body (Appendix F has the formulas from the running code). Each contact asks for a reference acceleration a_ref = −k·imp(r)·r − b·v and the convex solver blends it with the unconstrained acceleration by an impedance. (k, b) come from solref: reference format (τ, ζ) → k = 1/(dmax²τ²ζ²), b = 2/(dmax·τ), with the refsafe clamp τ ≥ 2·δt; or direct format (−k, −b) unclamped. k is an acceleration per metre, so the force scales with the pair's effective mass: the same solref makes a heavier body stiffer in N/m.")
    nb.box("What this means for our arms", "Clutter MuJoCo arms: reference format calibrated so a resting 65 g sphere sinks m g/k at δt = 1 ms (τ = 2.4 ms at k = 10⁵). Ball arm: direct undamped (−2.24·10³, 0), because the scene asks for zero dissipation and the reference format cannot express it. Never let Newton's ke/kd → solref conversion set these (it produced ζ = 3.16 and ~100× softer contact). In the TRAINING scenes the rig and the mug use MujocoCollisionCfg(condim=6, solref=(0.02, 1.0)) — MuJoCo's default τ = 20 ms — which at a 1/90 s step is not clamped but is soft (Appendix F.4 gives the stiffness); that is a Part-2 configuration fact to state.")

    nb.h("A4. Convex contact solvers: ICF, and what 'ICF' is in our code", 1)
    nb.p("Todorov (2014) showed the MuJoCo step can be posed as a convex optimization. Castro et al.'s ICF (2023, 'irrotational contact fields') poses compliant point contact with regularized friction as an unconstrained convex minimization over next-step velocities: v_{n+1} = argmin ℓ(v; x_n, δt). Convex → a unique solution always exists and a Newton iteration finds it — no step can fail, which is what makes rejected steps cheap in CENIC.")
    nb.p("CENIC Sec. IV: the normal impulse is first order and fully implicit in the normal velocity (γ_n = δt(f_e − δt k v_n)_+ (1 − d v_n)_+); the tangential impulse is implicit in velocity with the normal impulse LAGGED from the start of the step ('Lagged' member of the ICF family). First-order accurate in time, very stable. Cost: a Newton solve with a few iterations, each a linear system — measured 2.7–6.9 ms per march iteration vs 1.6–2.1 ms for MuJoCo on hard clutter (one world), and 40–60× per world per step at ≥ 2¹⁰ worlds.")
    nb.p("In our repos 'ICF' = icf_warp_adaptive's SolverICF (contact_law.py: 'Discrete Hunt & Crossley contact law (lagged)'; exact line search; single precision; IcfParams: contact_stiffness 1e5, contact_hc_dissipation 10.0, contact_stiction_tolerance 1e-4, contact_sigma 1e-3, limit_beta 0.1, newton_max_iterations 100, newton_tolerance 1e-5, max_rigid_contact 128). It is the solver behind both ICF arms in Part 1 and Part 2.")
    nb.p("PD actuation inside ICF (kernels_dof.py): 'K = dt·kp + kd and b = kp(q_d − q_0) + kd·v_d + u_ff: no near-rigid modulation' — the joint PD enters the convex cost implicitly (CENIC Sec. V-C style), which is why ICF is stable at K_p = 10⁶ where MuJoCo's explicit joint gain diverges (B12).")

    nb.h("A5. Error-controlled integration and CENIC", 1)
    nb.p("Fixed-step integration picks δt once. Error-controlled integration picks it every step (CENIC Sec. II-C, eq. 3–4): take a step two ways, e = ‖x − x̂‖ ≈ c̄ δt^p is the local error; accept if e ≤ ε_acc; δt_new = δt·(ε_acc/e)^{1/p}; rejected steps are redone smaller. The user chooses one number, the accuracy, instead of δt.")
    nb.p("Step doubling (CENIC Sec. V-A, eqs. 21–24): one full step δt and two half steps δt/2 — three convex solves per attempt, only two geometry queries (x^n serves the full step and the first half; x^{n+1/2} the second); the two-half-step result is kept; ICF being first order, the difference is a second-order error estimate. Our norm is positions only, ℓ∞ over coordinates (S = I; the bottom row of CENIC's Fig. 10), which is why it does not see velocity-only or energy artifacts (B4, B12).")
    nb.p("Constants adopted verbatim (CENIC Alg. 1 / Drake CalcAdjustedStepSize, present in both solvers' code): k_Safe 0.9, hysteresis band (0.9, 1.2), max grow 5.0, min shrink 0.1, k_Init 0.1 (first attempt = 0.1·δt_max in the Part-1 arms; in training the seed is dt_inner_init = the fixed arm's step); δt_max = 0.1 s on clutter (10 ms on the ball and in RL); Newton tolerance rule ε_tol = max(10⁻³ ε_acc, 10⁻⁸) (CENIC eq. 34) applied by the Part-1 harness; measured effect on the march < 10 %, on wall < 5 %.")
    nb.box("Work-precision, the standard way to show this", "x: requested accuracy ε_acc (log, decreasing to the right). y: wall time per simulated second (log). Fixed-step results appear as horizontal levels at their δt. A missing point = failure or timeout (100 s per simulated second). Cost grows as ε^{−1/2} for a first-order scheme with a second-order estimate. Theme C of the literature review adds: measured error vs cost (against a reference) is the real work-precision diagram; requested-tolerance vs cost is acceptable only among error-controlled methods — that is why B9 exists.")

    nb.h("A6. GPU simulation: worlds, launches, and why adaptivity is not free", 1)
    nb.p("Warp/Newton run every world in the same kernel launch: one thread (or block) per world. A CUDA graph records a launch sequence once and replays it without CPU involvement. Anything that needs the CPU to decide ('are all worlds done?') is a host synchronization: the GPU drains, the CPU reads 4 bytes, decides, launches again — the dominant cost at small batch sizes.")
    nb.p("A batch pays for its slowest world: if one world needs 200 inner steps to cross a boundary and the others 3, the launch runs 200 times (done worlds masked). Per-world adaptivity pays only when the expensive phases are rare or short — impacts, not the whole horizon (B7).")
    nb.p("Determinism: floating-point sums on a GPU are done by many threads with atomics; the order changes run to run. On one body invisible; on a pile of 20 bodies amplified to millimetres within 0.3 s (B10). Neither ICF nor MuJoCo Warp has a deterministic mode.")

    nb.h("A7. What we built — the two adaptive solvers, in detail", 1)
    nb.p("Contract (both adaptive solvers): the environment manager calls solver.step_dt(dt_outer, state_0, state_1, control) / step(...): advance EVERY world to the boundary t + dt_outer; scripts never re-implement the inner loop and never call .numpy() inside the physics loop. Constraint always: dt_inner_min < dt_inner_init ≤ dt_inner_max.")
    nb.h("SolverMuJoCoAdaptive (newton-adaptive, 2130 lines; parity/icf-march)", 2)
    nb.bl(["At ICF-march parity (a24e1071 + 3d672820): growth by the elementary Drake law alone (no ceiling memory, no consec_rej); exhaustion latches diverged, freezes the last committed state and snaps the clock ('Divergence is an event the env terminates on, not a pardon'); floor accept keeps the rule-sized ideal_dt; error test = the paper's absolute tolerance (rtol 0); full narrow-phase query at x^n and x^(n+1/2) every attempt.",
           "Constructor: tol 1e-3, dt_inner_init 0.01, dt_inner_min 1e-12, dt_inner_max None (→ dt_outer), dt_mode per_world (only value), tiling ragged, max_substeps 256 (the benches use 4096), use_newton_contacts False.",
           "Inner loop entirely in MuJoCo coordinates (qpos/qvel); Newton state converted in once at boundary entry and out once at exit (with FK). Per iteration (one captured CUDA graph): clamp dt to the boundary (done worlds → dt = 0; sliver flag) → build the active-world list (tail compaction) → geometry at x^n → step-double (snapshot qpos/qvel/qacc_warmstart/act; full eval; restore; half eval via the shared forward prefix; geometry at x^{n+1/2}; second half) → position-only ℓ∞ error (NaN flagged per component; diverged → 1e10) → Drake controller (new = 0.9·δt·√(tol/e), deadband (0.9, 1.2), clamp [0.1, 5]·δt; accept iff e ≤ tol or new ≥ δt; at the floor accept and suspend the guarantee; diverged at the floor → latch) → masked commit/restore → advance time → dt cap → 'any world unfinished?' flag.",
           "Host sync: one 4-byte flag read per iteration (NEWTON_MJ_ADAPTIVE_GRAPH=1 default); the opt-in conditional tier (NEWTON_MJ_ADAPTIVE_CONDITIONAL=1) records the whole march as a wp.capture_while node with zero host syncs (mujoco_warp's scratch allocations hidden behind a per-call-site buffer cache).",
           "Other flags: NEWTON_ADAPTIVE_TAIL_COMPACT 1; NEWTON_ADAPTIVE_RTOL 0; NEWTON_ADAPTIVE_CONTACT_REFRESH 1 (diagnostic-only escape hatch when no pipeline is attached); NEWTON_MJ_ADAPTIVE_SHARED_FWD on (Euler/implicitfast only). A stale comment names NEWTON_ADAPTIVE_CONTACT_COUPLING with no env read.",
           "Known defect (B4): on the undamped ball at ε ≤ 1e-3 it gains ~5 % energy per impact while fixed MuJoCo at the same steps conserves — the step changes through the undamped soft constraint inject energy. Open."])
    nb.h("SolverICF / SolverICFAdaptive (icf_warp_adaptive; the reference arm)", 2)
    nb.bl(["SolverICF: (1) IcfContactPatches.compute() — free motion, per-body Jacobians, per-env dynamics blocks, ICF patch constraints; (2) IcfContactSolve.solve() — the Newton solve with exact line search under CUDA-graph conditionals; (3) position integration (semi-explicit Euler). Single precision. Contact law: gamma_n(v_n) = dt·(fe0 − dt·k·v_n)_+ · (1 − d·v_n)_+ (lagged Hunt & Crossley), friction a regularized cone on the lagged tangential speed. PD embedded implicitly (K = dt·kp + kd). Joint limits near-rigid with R = ε·diag(A)^-1, ε = β²/(4π²)(1 + β/π), β = limit_beta 0.1.",
           "SolverICFAdaptive ('CENIC first-order step-doubling march over the ICF stages; the same IcfParams reaches both arms of a fixed/adaptive comparison, so only the stepping scheme differs'): IcfAdaptiveParams mode adaptive, tol 1e-3, dt_inner_init 1/90 (in RL: the fixed arm's step), dt_inner_min 0.0 (no floor), max_substeps 256, rtol 0. March body: stage dt → masked collide at x^n → full eval (warm v_n) → half-1 (warm (v_n+v_full)/2, shares the patch build) → FK → collide at x^{n+1/2} → half-2 (warm v_full) → error → adapt → commit → FK → status; wp.capture_while when an outer capture is active; a boundary-close readout solve so contact forces are coherent for sensors.",
           "DEVIATIONS.md (six live deviations from CENIC): per-world δt/floor/cap; seed from dt_inner_init; fixed Newton tolerance (§VI-B not adopted in the solver — the Part-1 harness applies eq. 34 as an override); no Hessian reuse / cubic init ('Cholesky 0.3 % of GPU time … narrow-phase 84.5 %'); query masking / redundant re-query on reject; floorless sanity exit.",
           "Configured from IsaacLab via env vars (B18): ICF_CONTACT_STIFFNESS, ICF_HC_DISSIPATION, ICF_MAX_RIGID_CONTACT (default 128 silently drops contacts during grasps — use 1024/8192), NEWTON_ADAPTIVE_TOL, NEWTON_ADAPTIVE_MAX_SUBSTEPS, ICF_ADAPTIVE_DT_INIT/MIN/MAX/RTOL."])
    nb.h("adaptive_boundary.py (shared)", 2)
    nb.p("'March a per-world adaptive timestep until EVERY world reaches the control boundary: full-integrity bookkeeping, no abandonment, no forced completion — every committed step satisfied the error test (or a floor/divergence path that never commits garbage). Tail cost is bounded by tail compaction (work restricted to still-active worlds), never by giving up on stragglers.' Kernels: mark_unfinished (flag while any sim_time < next_time); _with_status (2 = solve failed, 'converge or throw'); _contained (failures stay per-world; sticky latch + counter). A quantile stop (ending the boundary when few worlds remain) was removed from the shared path ('remove abandonment and forced completion').")
    nb.h("The bench harness (part1/bench/four_arms.py)", 2)
    nb.p("Builds the four arms (MuJoCo fixed / error control, ICF fixed / error control), replays one captured CUDA graph per boundary for ALL arms (fairness; captured-vs-eager physics agrees to 1e-8), tracks exhaustion/iterations on device, sets contact budgets (NCONMAX/NJMAX 1024, ICF_MAX_RIGID_CONTACT 2048 ≥ 2× measured demand: ~520 contacts/world hard clutter for ICF, ~380 active for MuJoCo), applies each scene's explicit MuJoCo solref, K_INIT 0.1 and the eq. 34 Newton-tolerance rule. One subprocess per configuration ('repeated in-process solver builds corrupt GPU state (observed CUDA 700)').")

    nb.h("A8. The RL platform, the arm, and the tasks (Part 2 in one page; details in B17–B25)", 1)
    nb.bl(["Stack: IsaacLab fork (develop) on Newton via NewtonMJWarpManager; training with rsl_rl PPO; Python from ~/Documents/code/icra2027/.venv (export VIRTUAL_ENV explicitly — isaaclab.sh resolves it first); W&B project icra2027 for the campaign (smokes: rubato-trossen) + video every 300 env steps (~12.5 iterations); watch the videos before judging a run; kill doomed runs early.",
           "Robot: Trossen WXAI (WidowX AI) 6-DoF arm + parallel gripper on a stationary rig (rails variant TROSSEN_RAILS=1 in the campaign). Vendor gains kp/kv 200/10, 100/5, 50/5, gripper 1000/50; vendor velocity limits 3.375/7.0/7.0 rad/s, gripper 0.0875 m/s (authored only as PhysX-namespaced USD attrs Newton never read — fixed 1a61ab0c88).",
           "Control: sim.dt 1/90 s, decimation 3 → 30 Hz policy; the campaign ladder K1–K5 (1/30×1 … 1/150×5) varies the fixed step at constant control rate; the adaptive arm marches the same 1/30 s boundary from a 1/90 s seed (flip/tree pinned to 1/90×3 by explicit override).",
           "Objects: LBM mug (raw per-piece triangle meshes, fixed by decision in the shipped scene pass — no hull), plate (25 convex pieces), dish rack (raw mesh), table guard slab. Contact in MuJoCo terms: condim 6, solref (0.02, 1.0); friction mug 0.2, plate 0.3, pads 1.0, table 0.6. ICF contact: global IcfParams (stiffness from ICF_CONTACT_STIFFNESS — NOT exported by the campaign script; see B21 gap).",
           "Tasks on disk: lift (IsaacContrib-Lift-Mug-Trossen-v0), slide (…-Slide-Mug-…; moving goal at 0.20 m/s), plate (…-PlatePick-…), flip (…-Flip-Mug-…), tree (…-MugHang-…). Per-task exploration recipe is 'the law' (d23f9b8cdc): lift init_std 0.5 / range (0.05, 1.5), arm scale 0.1, gripper 0.05; slide and plate 1.5 / (0.05, 3.0), wide arm scale {0.5, 1.0, 1.5}, gripper 0.15; flip per-dim init_std [0.12, 0.12, 0.12, 0.40, 0.05, 0.50, 0.30, 0.30], scalar 0.05 / (0.05, 2.5) (08-28/29 redesign); tree 0.5 / (0.05, 3.0), arm {0.5, 1.0}, gripper 0.05. Entropy 0.006 except flip/tree 0.0; lr 1e-4 adaptive; 8192 envs in the configs, 2048 in the campaign; seed 42.",
           "Shared success gate: object within 5 cm of the goal, tilt ≤ acos(0.87), held 30 consecutive steps (lift/plate/flip); slide: tracked ≥ 95 % of steps against the FINAL target's gates (since 2015428e19). Terminations: robot_abnormal (joint vel > 25), physics_diverged, time_out, object_off_table (slide/flip); early_termination reward −50 (bc8e951e89: 'the policy learns to crush the mug until the solve breaks').",
           "Hardware: flip and slide on the real WXAI are Marco's; the deployment brief (B28) says: goal_time 0.1 s at 30 Hz, tolerances 0 while new, gripper cap 100 N, derive sim gains from the cascade and measure a step response."])
